[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.5"

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.rocket]
version = "0.5.1"
features = ["json"]