openapi: 3.0.0
info:
  title: Restaurant API
  description: Simple API for keeping track of orders in a restaurant.
  version: 0.1.9
tags:
  - name: orders
    description: Orders currently being processed
  - name: menu-items
    description: All possible items which can be ordered
paths:
  /orders/{table-id}:
    get:
      tags:
        - orders
      summary: Get all remaining orders for a table
      parameters:
        - name: table-id
          in: path
          description: The table ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  menu-items:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        menu-item-id:
                          type: number
                        menu-item-name:
                          type: string
    post:
      tags:
        - orders
      summary: Adds orders to a table
      description: Note that an order-id is required. This can be any integer, as long as it doesn't have the same ID as any other order at that table.
      parameters:
        - name: table-id
          in: path
          description: The table ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                orders:
                  type: array
                  items:
                    type: object
                    properties:
                      order-id:
                        type: number
                      menu-item-id:
                        type: number
      responses:
        '200':
          description: Success
        '400':
          description: Malformed request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Format of data in body is incorrect"
        '404':
          description: Table does not exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Table with id 1 does not exist"
        '422':
          description: Invalid item-id or duplicate item-id
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Menu item with id 1 does not exist"
  /orders/{table-id}/{order-id}:
    get:
      tags:
        - orders
      summary: Get information for a specific order of a specific table
      parameters:
        - name: table-id
          in: path
          description: The table ID
          required: true
          schema:
            type: string
        - name: order-id
          in: path
          description: The Order ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  order-id:
                    type: string
                  menu-item-id:
                    type: number
                  menu-item-name:
                    type: string
                  minutes-to-cook:
                    type: number
        '404':
          description: Table or Order does not exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Table with id 1 does not exist"
    delete:
      tags:
        - orders
      summary: Delete a given order from a table
      parameters:
        - name: table-id
          in: path
          description: The table ID
          required: true
          schema:
            type: string
        - name: order-id
          in: path
          description: The Order ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
        '404':
          description: Table or Order does not exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Table with id 1 does not exist"
  /menu-items:
    get:
      tags:
        - menu-items
      summary: Get all menu items in the database
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  menu-items:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string